name: build sigsci-cloudfoundry-buildpack
on:
  push:
    branches: bbucher-23974-release-pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Version
        run: |
          echo ::set-env name=VERSION::$(cat VERSION)
      - name: Rename README
        run: |
          echo "Version: ${VERSION}" > README.md
          mv README.md README-SIGSCI.md
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.VERSION }}
          name: "Release ${{ env.VERSION }}"
          body: |
            Changes in this Release
            - Adds GitHub Actions pipeline
          artifacts: "bin/*,lib/*,README-SIGSCI.md"
          token: ${{ secrets.GITHUB_TOKEN }}