name: build sigsci-cloudfoundry-buildpack
on:
  push:
    branches: bbucher-23974-release-pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./make.sh
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - Adds GitHub Actions pipeline
            draft: false
            prerelease: false