name: build sigsci-cloudfoundry-buildpack
on:
  push:
    branches: bbucher-23974-release-pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Version
        run: |
          echo ::set-env name=VERSION::$(cat VERSION)
      - name: Rename README
        run: |
          echo "Version: ${VERSION}" > README-SIGSCI.md
          cat README.md >> README-SIGSCI.md
          echo "Version: ${VERSION}" > README.md
          mv README.md README-SIGSCI.md

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: |
            Changes in this Release
            - Adds GitHub Actions pipeline
            draft: false
            prerelease: false