name: release sigsci-cloudfoundry-buildpack
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Release Asset
        run: |
          tar -zcvf sigsci-cloudfoundry-buildpack.tar.gz bin/ lib/
      - name: Get Upload URL
        run: |
          echo ::set-env name=RELEASE_URL::${{ github.event.release.assets_url }}
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.RELEASE_URL }}
          asset_path: ./sigsci-cloudfoundry-buildpack.tar.gz
          asset_name: sigsci-cloudfoundry-buildpack.tar.gz
          asset_content_type: application/gzip
