name: build sigsci-cloudfoundry-buildpack
on:
  push:
    branches: bbucher-23974-release-pipeline
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Get Version
        run: |
          echo ::set-env name=VERSION::$(cat VERSION)
      - name: Rename README
        run: |
          echo "Version: ${VERSION}" > README-SIGSCI.md
          cat README.md >> README-SIGSCI.md
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README-SIGSCI.md
          git commit -m "Rename README.md to README-SIGSCI.md" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ env.VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -u ${{ github.actor }}:${{ github.token }} -d '{"tag_name":"${{ env.VERSION }}", "target_commitish":"${{ env.VERSION }}", "name":"Release ${{ env.VERSION }}", "draft":false, "prerelease":false}' -H "Content-Type: application/json" -X POST https://api.github.com/repos/signalsciences/sigsci-cloudfoundry-buildpack/releases