name: release sigsci-cloudfoundry-buildpack
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Create Release Asset
        run: |
          zip -r sigsci-cloudfoundry-buildpack.zip bin lib
      - name: Get Upload URL
        run:
          echo UPLOAD_URL=${{ github.event.release.upload_url }} >> $GITHUB_ENV
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./sigsci-cloudfoundry-buildpack.zip
          asset_name: sigsci-cloudfoundry-buildpack.zip
          asset_content_type: application/zip

